var defaultEngines = [
		{"searchForm":null,"query_string":"https://www.google.com/search?q={searchTerms}&ie=utf-8&oe=utf-8&client=firefox-b-1-ab&client=firefox-b-1","icon_url":"http://google.com/favicon.ico","title":"Google","order":1,"icon_base64String":"","method":"GET","params":[{"name":"q","value":"{searchTerms}"},{"name":"ie","value":"utf-8"},{"name":"oe","value":"utf-8"},{"name":"client","value":"firefox-b-1-ab","purpose":"keyword"},{"name":"client","value":"firefox-b-1","purpose":"searchbar"}],"template":"https://www.google.com/search","queryCharset":"UTF-8","hidden":false},
		{"searchForm":null,"query_string":"https://www.amazon.com/exec/obidos/external-search/?field-keywords={searchTerms}&ie={inputEncoding}&mode=blended&tag=mozilla-20&sourceid=Mozilla-search","icon_url":"http://amazon.com/favicon.ico","title":"Amazon.com","order":2,"icon_base64String":"","method":"GET","params":[{"name":"field-keywords","value":"{searchTerms}"},{"name":"ie","value":"{inputEncoding}"},{"name":"mode","value":"blended"},{"name":"tag","value":"mozilla-20"},{"name":"sourceid","value":"Mozilla-search"}],"template":"https://www.amazon.com/exec/obidos/external-search/","queryCharset":"UTF-8","hidden":false},
		{"searchForm":"https://www.facebook.com/","query_string":"https://www.facebook.com/search/top/?q={searchTerms}&opensearch=1?","icon_url":"http://facebook.com/favicon.ico","title":"Facebook","order":57,"icon_base64String":"","method":"GET","params":[],"template":"https://www.facebook.com/search/top/?q={searchTerms}&opensearch=1","queryCharset":"UTF-8","hidden":false},
		{"searchForm":"http://www.youtube.com","query_string":"http://www.youtube.com/results?search_type=search_videos&search_query={searchTerms}&search_sort=relevance&search_category=0&page={startPage?}","icon_url":"http://youtube.com/favicon.ico","title":"YouTube","order":7,"icon_base64String":"","method":"GET","params":[{"name":"search_type","value":"search_videos"},{"name":"search_query","value":"{searchTerms}"},{"name":"search_sort","value":"relevance"},{"name":"search_category","value":"0"},{"name":"page","value":"{startPage?}"}],"template":"http://www.youtube.com/results","queryCharset":"UTF-8","hidden":false},
		{"searchForm":null,"query_string":"https://twitter.com/search?q={searchTerms}&partner=Firefox&source=desktop-search","icon_url":"http://twitter.com/favicon.ico","title":"Twitter","order":19,"icon_base64String":"","method":"GET","params":[{"name":"q","value":"{searchTerms}"},{"name":"partner","value":"Firefox"},{"name":"source","value":"desktop-search"}],"template":"https://twitter.com/search","queryCharset":"UTF-8","hidden":false},
		{"searchForm":"http://www.pinterest.com/search/pins/","query_string":"http://www.pinterest.com/search/pins/?q={searchTerms}?","icon_url":"http://pinterest.com/favicon.ico","title":"Pinterest","order":58,"icon_base64String":"","method":"GET","params":[],"template":"http://www.pinterest.com/search/pins/?q={searchTerms}","queryCharset":"UTF-8","hidden":false},
		{"searchForm":null,"query_string":"https://www.bing.com/search?q={searchTerms}&pc=MOZI&form=MOZCON&form=MOZSBR&form=MOZSPG&form=MOZLBR&form=MOZTSB","icon_url":"http://bing.com/favicon.ico","title":"Bing","order":15,"icon_base64String":"","method":"GET","params":[{"name":"q","value":"{searchTerms}"},{"name":"pc","value":"MOZI"},{"name":"form","value":"MOZCON","purpose":"contextmenu"},{"name":"form","value":"MOZSBR","purpose":"searchbar"},{"name":"form","value":"MOZSPG","purpose":"homepage"},{"name":"form","value":"MOZLBR","purpose":"keyword"},{"name":"form","value":"MOZTSB","purpose":"newtab"}],"template":"https://www.bing.com/search","queryCharset":"UTF-8","hidden":false},
		{"searchForm":null,"query_string":"https://duckduckgo.com/?q={searchTerms}&t=ffcm&t=ffab&t=ffsb&t=ffhp&t=ffnt","icon_url":"http://duckduckgo.com/favicon.ico","title":"DuckDuckGo","order":18,"icon_base64String":"","method":"GET","params":[{"name":"q","value":"{searchTerms}"},{"name":"t","value":"ffcm","purpose":"contextmenu"},{"name":"t","value":"ffab","purpose":"keyword"},{"name":"t","value":"ffsb","purpose":"searchbar"},{"name":"t","value":"ffhp","purpose":"homepage"},{"name":"t","value":"ffnt","purpose":"newtab"}],"template":"https://duckduckgo.com/","queryCharset":"UTF-8","hidden":false},
		{"searchForm":"https://www.ebay.com/","query_string":"https://rover.ebay.com/rover/1/711-53200-19255-0/1?ff3=4&toolid=20004&campid=5338192028&customid=&mpre=https://www.ebay.com/sch/{searchTerms}","icon_url":"http://ebay.com/favicon.ico","title":"eBay","order":3,"icon_base64String":"","method":"GET","params":[{"name":"ff3","value":"4"},{"name":"toolid","value":"20004"},{"name":"campid","value":"5338192028"},{"name":"customid","value":""},{"name":"mpre","value":"https://www.ebay.com/sch/{searchTerms}"}],"template":"https://rover.ebay.com/rover/1/711-53200-19255-0/1","queryCharset":"UTF-8","hidden":false}
];	