var defaultEngines = [
	{
		"type": "searchEngine",
		"searchForm": "https://www.google.com/",
		"template": "https://www.google.com/search?q={searchTerms}",
		"icon": "/defaultEnginesIcons/google.svg",
		"title": "Google",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://www.amazon.com/",
		"template": "https://www.amazon.com/exec/obidos/external-search/?field-keywords={searchTerms}&ie={inputEncoding}&mode=blended",
		"icon": "/defaultEnginesIcons/amazon.svg",
		"title": "Amazon.com",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://www.facebook.com/",
		"template": "https://www.facebook.com/search/top/?q={searchTerms}&opensearch=1",
		"icon": "/defaultEnginesIcons/facebook.svg",
		"title": "Facebook",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "http://www.youtube.com",
		"template": "http://www.youtube.com/results?search_query={searchTerms}",
		"icon": "/defaultEnginesIcons/youtube.svg",
		"title": "YouTube",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://twitter.com/",
		"template": "https://twitter.com/search?q={searchTerms}&source=desktop-search",
		"icon": "/defaultEnginesIcons/twitter.svg",
		"title": "Twitter",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "http://www.pinterest.com/search/pins/",
		"template": "http://www.pinterest.com/search/pins/?q={searchTerms}",
		"icon": "/defaultEnginesIcons/pinterest.svg",
		"title": "Pinterest",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://www.bing.com/",
		"template": "https://www.bing.com/search?q={searchTerms}",
		"icon": "/defaultEnginesIcons/bing.svg",
		"title": "Bing",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://duckduckgo.com/",
		"template": "https://duckduckgo.com/?q={searchTerms}",
		"icon": "/defaultEnginesIcons/duckduckgo.svg",
		"title": "DuckDuckGo",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://www.ebay.com/",
		"template": "https://www.ebay.com/sch/i.html?_nkw={searchTerms}",
		"icon": "/defaultEnginesIcons/ebay.svg",
		"title": "eBay",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://en.wikipedia.org/",
		"template": "https://en.wikipedia.org/wiki/Special:Search?search={searchTerms}",
		"icon": "/defaultEnginesIcons/wikipedia.svg",
		"title": "Wikipedia (en)",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://www.google.com",
		"template": "https://www.google.com/search?q=site%3A{selectdomain}+{searchTerms}",
		"icon": "/defaultEnginesIcons/google_site.svg",
		"title": "Google Site Search",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	}
];